version: 2.1
executors:
  inbac:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/inbac
jobs:
  build:
    executor: inbac
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install Dependencies
          command: |
            poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
  test:
    executor: inbac
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Run tests
          command: |
            poetry run test

workflows:
    version: 2
    build_and_test:
      jobs:
        - build
        - test:
            requires:
              - build